const setImages: { [key: string]: string } = {
    "The Great Dark Beyond": "/images/sets/the-great-dark-beyond.png",
    "Base Set": "/images/sets/base-set.png",
    "Classic": "/images/sets/classic.png",
    "Basic": "/images/sets/classic.png",
    "Curse of Naxxramas": "/images/sets/curse-of-naxxramas.png",
    "Goblins vs Gnomes": "/images/sets/goblins-vs-gnomes.png",
    "Blackrock Mountain": "/images/sets/blackrock-mountain.png",
    "The Grand Tournament": "/images/sets/the-grand-tournament.png",
    "League of Explorers": "/images/sets/league-of-explorers.png",
    "Whispers of the Old Gods": "/images/sets/whispers-of-the-old-gods.png",
    "One Night in Karazhan": "/images/sets/one-night-in-karazhan.png",
    "Mean Streets of Gadgetzan": "/images/sets/mean-streets-of-gadgetzan.png",
    "Journey to Un’Goro": "/images/sets/journey-to-ungoro.png",
    "Knights of the Frozen Throne": "/images/sets/knights-of-the-frozen-throne.png",
    "Kobolds and Catacombs": "/images/sets/kobolds-and-catacombs.png",
    "The Witchwood": "/images/sets/the-witchwood.png",
    "The Boomsday Project": "/images/sets/the-boomsday-project.png",
    "Rastakhan’s Rumble": "/images/sets/rastakhans-rumble.png",
    "Rise of Shadows": "/images/sets/rise-of-shadows.png",
    "Saviors of Uldum": "/images/sets/saviors-of-uldum.png",
    "Descent of Dragons": "/images/sets/descent-of-dragons.png",
    "Galakrond’s Awakening": "/images/sets/galakronds-awakening.png",
    "Ashes of Outland": "/images/sets/ashes-of-outland.png",
    "Scholomance Academy": "/images/sets/scholomance-academy.png",
    "Madness at the Darkmoon Faire": "/images/sets/madness-at-the-darkmoon-faire.png",
    "Forged in the Barrens": "/images/sets/forged-in-the-barrens.png",
    "United in Stormwind": "/images/sets/united-in-stormwind.png",
    "Fractured in Alterac Valley": "/images/sets/fractured-in-alterac-valley.png",
    "TITANS": "/images/sets/titans.png",
    "Voyage to the Sunken City": "/images/sets/voyage-to-the-sunken-city.png",
    "March of the Lich King": "/images/sets/march-of-the-lich-king.png",
    "Whizbang's Workshop": "/images/sets/whizbangs-workshop.png",
    "Festival of Legends": "/images/sets/festival-of-legends.png",
    "Showdown in the Badlands": "/images/sets/showdown-in-the-badlands.png",
    "Perils in Paradise": "/images/sets/perils-in-paradise.png",
    "Murder at Castle Nathria": "/images/sets/murder-at-castle-nathria.png",
  };
  
  export default setImages;