const setImagesBoosters: { [key: string]: string } = {
    "The Great Dark Beyond": "/images/boosters/the-great-dark-beyond.png",
    "Base Set": "/images/boosters/base-set.png",
    "Classic": "/images/boosters/classic.png",
    "Basic": "/images/boosters/classic.png",
    "Curse of Naxxramas": "/images/boosters/curse-of-naxxramas.png",
    "Goblins vs Gnomes": "/images/boosters/goblins-vs-gnomes.png",
    "Blackrock Mountain": "/images/boosters/blackrock-mountain.png",
    "The Grand Tournament": "/images/boosters/the-grand-tournament.png",
    "League of Explorers": "/images/boosters/league-of-explorers.png",
    "Whispers of the Old Gods": "/images/boosters/whispers-of-the-old-gods.png",
    "One Night in Karazhan": "/images/boosters/one-night-in-karazhan.png",
    "Mean Streets of Gadgetzan": "/images/boosters/mean-streets-of-gadgetzan.png",
    "Journey to Un’Goro": "/images/boosters/journey-to-ungoro.png",
    "Knights of the Frozen Throne": "/images/boosters/knights-of-the-frozen-throne.png",
    "Kobolds and Catacombs": "/images/boosters/kobolds-and-catacombs.png",
    "The Witchwood": "/images/boosters/the-witchwood.png",
    "The Boomsday Project": "/images/boosters/the-boomsday-project.png",
    "Rastakhan’s Rumble": "/images/boosters/rastakhans-rumble.png",
    "Rise of Shadows": "/images/boosters/rise-of-shadows.png",
    "Saviors of Uldum": "/images/boosters/saviors-of-uldum.png",
    "Descent of Dragons": "/images/boosters/descent-of-dragons.png",
    "Galakrond’s Awakening": "/images/boosters/galakronds-awakening.png",
    "Ashes of Outland": "/images/boosters/ashes-of-outland.png",
    "Scholomance Academy": "/images/boosters/scholomance-academy.png",
    "Madness at the Darkmoon Faire": "/images/boosters/madness-at-the-darkmoon-faire.png",
    "Forged in the Barrens": "/images/boosters/forged-in-the-barrens.png",
    "United in Stormwind": "/images/boosters/united-in-stormwind.png",
    "Fractured in Alterac Valley": "/images/boosters/fractured-in-alterac-valley.png",
    "TITANS": "/images/boosters/titans.png",
    "Voyage to the Sunken City": "/images/boosters/voyage-to-the-sunken-city.png",
    "March of the Lich King": "/images/boosters/march-of-the-lich-king.png",
    "Whizbang's Workshop": "/images/boosters/whizbangs-workshop.png",
    "Festival of Legends": "/images/boosters/festival-of-legends.png",
    "Showdown in the Badlands": "/images/boosters/showdown-in-the-badlands.png",
    "Perils in Paradise": "/images/boosters/perils-in-paradise.png",
    "Murder at Castle Nathria": "/images/boosters/murder-at-castle-nathria.png",
    "Path of Arthas": "/images/boosters/path-of-arthas.png",
  };
  
  export default setImagesBoosters;